version: '3.7'

services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/users-list
      - /var/www/users-list/vendor
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/var/www/users-list
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
