version: '3.7'

services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/users-list
    tty: true
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/users-list
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app

  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
